[package]
name = "gfx_test"
version = "0.1.0"
authors = ["Andrey Lesnikov <ozkriff@gmail.com>"]

[dependencies]
glutin = "*"
gfx_core = "*"
gfx_device_gl = "*"
gfx_window_glutin = "*"
gfx = "*"

[dependencies.image]
version = "*"
default-features = false
features = ["png_codec"]
